export interface Job {
  id: string;
  title: string;
  company: string;
  companyLogo?: string;
  location: string;
  url: string;
  tags: string[];
  salary?: string;
  date: string;
  source: "Remotive" | "Adzuna";
  jobType?: string;
}

export type JobFilter = "all" | "ai-ml" | "data" | "engineering" | "devops";

interface CachedJob {
  id: string;
  title: string;
  company: string;
  companyLogo?: string;
  location: string;
  url: string;
  tags: string[];
  salary?: string;
  postedAt: string;
  source: "Remotive" | "Adzuna";
  jobType?: string;
}

interface JobsCache {
  lastUpdated: string;
  count: number;
  jobs: CachedJob[];
}

function timeAgo(dateStr: string): string {
  const now = new Date();
  const date = new Date(dateStr);
  const diffMs = now.getTime() - date.getTime();
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
  if (diffHours < 1) return "Just now";
  if (diffHours < 24) return `${diffHours}h ago`;
  const diffDays = Math.floor(diffHours / 24);
  if (diffDays === 1) return "1d ago";
  if (diffDays < 7) return `${diffDays}d ago`;
  const diffWeeks = Math.floor(diffDays / 7);
  if (diffWeeks === 1) return "1w ago";
  return `${diffWeeks}w ago`;
}

// Filter keywords to match jobs against categories
const FILTER_KEYWORDS: Record<string, string[]> = {
  "ai-ml": ["ai", "ml", "machine learning", "artificial intelligence", "deep learning", "nlp", "computer vision", "neural"],
  data: ["data science", "data analyst", "data engineer", "analytics", "data"],
  engineering: ["software engineer", "developer", "backend", "frontend", "full stack", "sde"],
  devops: ["devops", "sre", "cloud", "infrastructure", "platform engineer", "kubernetes"],
};

function matchesFilter(job: CachedJob, filter: JobFilter): boolean {
  if (filter === "all") return true;
  const keywords = FILTER_KEYWORDS[filter] || [];
  const text = `${job.title} ${job.tags.join(" ")}`.toLowerCase();
  return keywords.some((kw) => text.includes(kw));
}

export async function fetchJobs(filter: JobFilter = "all"): Promise<Job[]> {
  // Read from static cache (generated by scripts/refresh-jobs.ts)
  const res = await fetch("/jobs-cache.json");
  if (!res.ok) throw new Error("Jobs cache not found. Run: npx tsx scripts/refresh-jobs.ts");

  const cache: JobsCache = await res.json();

  return cache.jobs
    .filter((j) => matchesFilter(j, filter))
    .map((j) => ({
      ...j,
      date: timeAgo(j.postedAt),
    }));
}

export function getLastUpdated(cache: { lastUpdated: string }): string {
  return timeAgo(cache.lastUpdated);
}

export const jobFilterLabels: Record<string, string> = {
  all: "All Roles",
  "ai-ml": "AI / ML",
  data: "Data",
  engineering: "Engineering",
  devops: "DevOps",
};
